resources:
- repo: self
  fetchDepth: 1
queue:
  name: Hosted Ubuntu 1604
trigger:
- master
variables:
  TargetFramework: 'netcoreapp5.0'
  RestoreBuildProjects: 'gamitude_backend/*.csproj'
  BuildConfiguration: 'Release'
  DockerImageName: 'gamitude/backend'
steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(RestoreBuildProjects)'
    feedsToUse: select
    includeNuGetOrg: true # Required when feedsToUse == Select
    #feedsToUse: config
    #nugetConfigPath: ./nuget/
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(RestoreBuildProjects)'
    arguments: '--configuration $(BuildConfiguration) --framework=$(TargetFramework)'
    
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --framework=$(TargetFramework)'
    zipAfterPublish: false
    modifyOutputPath: false

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'cd gamitude_backend && docker build -t gamitude/backend:latest .'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'docker save --output $(build.artifactstagingdirectory)/gamitude_backend.tar gamitude/backend'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
